# Generated by Django 5.1.6 on 2025-03-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='public', max_length=20),
            preserve_default=False,
        ),
    ]
