export {default as AddEvent} from './addEvent/addEvent.jsx'
export {default as EventInfo} from './eventInfo/event.jsx'
export {default as Home} from './home/home.jsx'
export {default as Profile} from './profile/profilePage.jsx'
export {default as Settings} from './settings/settings.jsx'
